### ISSUE TITLE
Develop User Profile Services and Expose Relevant APIs

### ISSUE THREAD

**Issue by eroma2014** [NASA-IMPACT/veda-auth-central#18]
### Description
Create a robust user profile service that manages user data efficiently and exposes relevant APIs for client applications. This project aims to enhance user experience, facilitate authentication, and provide seamless access to user profiles.

### Tasks

- [x] Design the User Profile Service
1. Define the user profile service requirements, considering scalability, availability, and performance.
2. Decide on the data model for user profiles
3. Choose an appropriate database technology.
4. Design API endpoints for CRUD operations on user profiles.
- [x] Implementation
1. Set up the project structure.
2. Create the necessary database schema and tables.
3. Implement authentication mechanisms for API access.
- [x] Sevirce APIs
1. Implement the Service APIs
2. Performance Testing and Optimization

Deployment and Monitoring
This would be carried forward for the service deployment stage of the development in the future. 
1. Deploy the service to a production environment
2. Set up monitoring and alerting for uptime, performance, and errors.
```[tasklist]
### Tasks
```

**Comment by lahirujayathilake** [comment]
This has been fixed in,

* https://github.com/NASA-IMPACT/veda-auth-central/commit/8dee77fc4502af71280a4abd33a4ab28a47a3de7
* https://github.com/NASA-IMPACT/veda-auth-central/commit/e5458916656c317ee2d2f4eb7ae0e7295f494825
* https://github.com/NASA-IMPACT/veda-auth-central/commit/268161eca1ddffa45ab27295432aac9e06486533

The performance test will be done after all the APIs are developed and will be addressed in - #39
