### ISSUE TITLE
Inject scopes for Grafana authorization

### ISSUE THREAD

**Issue by smohiudd** [NASA-IMPACT/veda-auth-central#65]
## Description

The VEDA `dev` Grafana instance has been deployed and incorporates authentication: https://d1z1g2cnqbz2id.cloudfront.net/

Authorization is needed to allow user memberships to certain groups such as `admin`, `editor`, `viewer` etc. The veda-monitoring repo currently uses [role mapping with the role_attribute_path](https://github.com/NASA-IMPACT/veda-monitoring/blob/5ea4470eba7f568be997f2038349963a13827a70/stacks/grafana.py#L327) (currently tested with Github) which can also be [configured with Grafana](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/generic-oauth/#configure-role-mapping). 

Veda Auth Central/Keycloak will need to inject scopes into tokens which can then be inspected by the Grafana client using the role mappings. 

cc: @alukach

**Comment by alukach** [comment]
I wrote a duplicate ticket (#72), my thoughts from there:

To implement nuanced authorization controls for Grafana, we need the `id_token` or `access_token` to contain information about the user that we can use to determine the user's access. Within Grafana, we have three roles: `Admin`, `Editor`, and `Viewer`. Grafana accepts a [JMESPath expression](https://jmespath.org/) to interrogate the ID Token returned by VEDA Auth Central and to determine which role (if any) the user will be granted.  This pattern makes for great flexibility in adapting to the format of VEDA Auth Central (ie we can format the ID token in any way we see fit).

There's a larger question around how we want to manage permissions associated with users within VEDA Auth Central. My first thought is that we approach this via Scopes -> Roles -> Groups -> Users.

Regarding scopes, I recommend that we use the following three client scopes:

* `grafana:viewer`
* `grafana:editor`
* `grafana:admin`

For roles, we should follow a similar pattern:

* `GrafanaViewer` (has `grafana:viewer` scope)
* `GrafanaEditor` (has `grafana:editor` scope)
* `GrafanaAdmin` (has `grafana:admin` scope)

For groups, this could be a bit more general:

* `SystemAdmin` contains `GrafanaAdmin`
* `SystemOperator` contains `GrafanaEditor`
* `SystemViewer` contains `GrafanaViewer`

We would then use the following JMES path ([playground](https://play.jmespath.org/?u=9d881f26-fbdb-4efc-816e-1946dc204670)):

```jmespath
contains(scopes, 'grafana:admin') && 'Admin' || contains(scopes, 'grafana:editor') && 'Editor' || contains(scopes, 'grafana:viewer') && 'Viewer'
```

We will set the `role_attribute_strict` flag to `true` in order to deny access from any users without membership to one of these groups:

> Set to `true` to deny user login if the Grafana org role cannot be extracted using `role_attribute_path` or `org_mapping`. For more information on user role mapping, refer to [Configure role mapping](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/generic-oauth/#configure-role-mapping).]

**Comment by lahirujayathilake** [comment]
@alukach I have deployed the required changes, and you can start integrating.

The required configuration change for Grafana's defaults.ini file is:
`role_attribute_path = contains(groups, 'GrafanaAdmin') && 'Admin' || contains(groups, 'GrafanaEditor') && 'Editor' || contains(groups, 'GrafanaViewer') && 'Viewer'`

I created three groups: GrafanaAdmin, GrafanaEditor, and GrafanaViewer. You(anthony@developmentseed.org) and @smohiudd(saadiq@developmentseed.org) have already been added as administrators of these groups, so you can add members as needed.

Until the admin dashboard is ready, you can use the following API to add users to the groups: https://api.veda.usecustos.org/swagger-ui/index.html#/Group%20Management/addUserToGroup

Here's a curl command example:

`curl -X POST https://api.veda.usecustos.org/api/v1/group-management/groups/GrafanaEditor/members \
-H "Authorization: Bearer <token>" \  # Replace <token> with your actual token
-H "client_id: veda-n78pbpiu8msdjjxkvlmb-10000000" \
-H "Content-Type: application/json" \
-d '{
  "username": "xyz@gmail.com",
  "type": "MEMBER"
}'
`

**Comment by lahirujayathilake** [comment]
This has already been resolved
